### PR TITLE
Added another unit test that failed

### PR DESCRIPTION
**Pull request by john-zli**
Added a test case that failed.

### CODE REVIEW

**Comment by Nancers** [comment]
looks good

**Comment by jfeng94** [comment]
Wow John you have terrible coding style 0/10 would not read again.

Also something seems to be borken. Halp.

**Comment by john-zli** [comment]
Teh most quality comments I've ever received.

**Comment by john-zli** [comment]
I'm merging :)

**Comment by jfeng94** [comment]
WHOOOOP WHOOOOOOOOOOP

**Pull request merged**
